algoritmo "imprima de n1 a n2"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

n1, n2, cont: inteiro

inicio

escreva("Digite o primeiro número:")
leia(n1)
escreva("Digite o segundo número:")
leia(n2)


para cont de n1 ate n2 faca
    escreval(cont)
fimpara

fimalgoritmo