algoritmo "Imprimir numero par"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

cont:inteiro

inicio

para cont de 100 ate 150 passo 2 faca
    escreval("O número ", cont, " é par.")
fimpara

fimalgoritmo