algoritmo "1"
// Disciplina : [Lógica de programação]
// Professora : Bruna Sozzo
// Descrição : O algoritmo calcula a media de combustivel ultilizado por KM
// Autor(a) : Gabriel Yuki Silva Koga
// Data atual : 21/02/2025
var
    c: real
    km: real
inicio
    escreval("Digite a quantidade de km andados")
    leia(km)
    escreval("Digite a quantidade de litros consumidos")
    leia(c)
    escreval("A media de combustivel ultilizado por KM é de: ", km / c)

fimalgoritmo