algoritmo "Média do Aluno"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Brunna Sozzo]
// Descrição   : 
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

media: inteiro

inicio

escreva("Digite a media do aluno: ")
leia(media)

se (media >= 60) entao
    escreval("Aprovado")
fimse
se (media <= 59) entao
        escreval("Recuperacao")

    fimse


fimalgoritmo