algoritmo "Estrutura de repetição para"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Yuki Silva Koga
// Data atual  : 03/04/2025
var

cont: inteiro
teste: inteiro

inicio

teste <- 1

para cont de teste ate 100000 passo 2 faca
    escreval("O número ", cont, " é impar.")
fimpara

fimalgoritmo