algoritmo "Imprimir numero par somas"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

cont, soma:inteiro

inicio


para cont de 100 ate 200 passo 2 faca
    soma <- cont + soma
fimpara

escreval("A soma dos números pares de 100 a 200 é: ", soma)

fimalgoritmo