algoritmo "Soma de inteiro"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

cont: inteiro
N: inteiro

inicio

cont <- 0

enquanto (cont <= 100) faca
    N <- cont + N
    cont <- cont + 1
fimenquanto


fimalgoritmo