algoritmo "somaDeMultiplos"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var

multiplo: real
cont: inteiro

inicio

escreva("Digite o número: ")
leia(multiplo)

cont <- 1

enquanto (cont <= 10) faca

    escreval(multiplo * cont)

    cont <- cont + 1
fimenquanto

fimalgoritmo